// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASkNptHLx5MihgNF7t28v47_4tkJL0CPg',
    appId: '1:152601554868:web:af9b8ee94560fd05c10ce1',
    messagingSenderId: '152601554868',
    projectId: 'emergency-resource-finde-c88c5',
    authDomain: 'emergency-resource-finde-c88c5.firebaseapp.com',
    storageBucket: 'emergency-resource-finde-c88c5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB896Hyu9Hb53JhT1LDhftQLUybInvuBSY',
    appId: '1:152601554868:android:f7eb95eac4e12656c10ce1',
    messagingSenderId: '152601554868',
    projectId: 'emergency-resource-finde-c88c5',
    storageBucket: 'emergency-resource-finde-c88c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAbZIm63AFOt1mE0oIT0Rb_jZHjMR-0-k',
    appId: '1:152601554868:ios:1579f766a1ad6f30c10ce1',
    messagingSenderId: '152601554868',
    projectId: 'emergency-resource-finde-c88c5',
    storageBucket: 'emergency-resource-finde-c88c5.firebasestorage.app',
    iosBundleId: 'com.example.emergencyResLocNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAbZIm63AFOt1mE0oIT0Rb_jZHjMR-0-k',
    appId: '1:152601554868:ios:1579f766a1ad6f30c10ce1',
    messagingSenderId: '152601554868',
    projectId: 'emergency-resource-finde-c88c5',
    storageBucket: 'emergency-resource-finde-c88c5.firebasestorage.app',
    iosBundleId: 'com.example.emergencyResLocNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASkNptHLx5MihgNF7t28v47_4tkJL0CPg',
    appId: '1:152601554868:web:170426602e256199c10ce1',
    messagingSenderId: '152601554868',
    projectId: 'emergency-resource-finde-c88c5',
    authDomain: 'emergency-resource-finde-c88c5.firebaseapp.com',
    storageBucket: 'emergency-resource-finde-c88c5.firebasestorage.app',
  );
}
